variables:
  MAVEN_VERSION: "3.6.3-jdk-11"
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

.test-junit-auth-postgres:
  image: ${PRIVATE_REGISTRY_PULL}/maven:${MAVEN_VERSION}
  services:
    - name: ${PRIVATE_REGISTRY_PULL}/postgres:12.3
      alias: postgresdb
  variables:
    POSTGRES_DB: testing
    POSTGRES_USER: testing
    POSTGRES_PASSWORD: testing
    DATABASE_HOST: postgresdb
    DATABASE_USER: $POSTGRES_USER
    DATABASE_PASSWORD: $POSTGRES_PASSWORD
    DATABASE_NAME: $POSTGRES_DB
    DATABASE_PORT: 5432
#  script:
#    - mvn -s $M2_PROXY_XML $MAVEN_CLI_OPTS clean jacoco:prepare-agent test jacoco:report
#  after_script:
#    - mvn -s $M2_PROXY_XML sonar:sonar -Dsonar.projectKey=$CI_PROJECT_ID-$CI_DEFAULT_BRANCH -Dsonar.host.url=$URL_SONAR -Dsonar.login=$AUTH_SONAR -Dmaven.test.failure.ignore=false
#  tags:
#    - docker
#  only:
#    - /-release/
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

